# Generated by Django 5.0.1 on 2024-12-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0004_approveddocuments_xml_file_pendingdocuments_xml_file'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fav_docs',
            field=models.ManyToManyField(blank=True, related_name='fav_docs', to='Documents.approveddocuments'),
        ),
    ]
