# Generated by Django 4.2.17 on 2024-12-16 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_profile_fav_docs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fav_docs',
        ),
    ]
