# Generated by Django 4.2.17 on 2024-12-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0005_page_act'),
        ('Users', '0003_remove_profile_fav_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fav_docs',
            field=models.ManyToManyField(blank=True, related_name='fav_docs', to='Documents.act'),
        ),
    ]
