# Generated by Django 5.0.1 on 2024-11-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_pendingdocuments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approveddocuments',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='pendingdocuments',
            name='image_url',
        ),
        migrations.AddField(
            model_name='approveddocuments',
            name='image',
            field=models.ImageField(default='document_images/default.jpg', upload_to='document_images/'),
        ),
        migrations.AddField(
            model_name='pendingdocuments',
            name='image',
            field=models.ImageField(default='document_images/default.jpg', upload_to='document_images/'),
        ),
    ]
