# Generated by Django 5.0.1 on 2024-12-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0003_remove_approveddocuments_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approveddocuments',
            name='xml_file',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pendingdocuments',
            name='xml_file',
            field=models.TextField(default=''),
        ),
    ]
