# Generated by Django 4.2.17 on 2024-12-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0004_approveddocuments_xml_file_pendingdocuments_xml_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='document_images/default.jpg', upload_to='document_images/')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('author', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('xml_file', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('pages', models.ManyToManyField(to='Documents.page')),
            ],
        ),
    ]
