# Generated by Django 4.2.17 on 2024-12-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0005_page_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='year',
            field=models.CharField(default='00/00/0000', max_length=10),
        ),
    ]
